### ISSUE TITLE
[FeatureRequest] Support for checking an attributes value

### ISSUE THREAD

**Issue by PhilippMDoerner** [Yandall/HTest#1]
Thanks for writing this package!
A really nice extension of its capabilities would be not just to check what attributes it has, but also whether a given attribute has a specific value.

A very typical usecase for that could be to check whether an anchor tag has a `href` attribute with the correct URL attached.
So a scenario like this:

```nim
  test """
    Given a server with snorlogue and 1 registered model
    When requesting 'overview' frontend Page
    Then it should return HTML with a table containing 1 model with a model link 
  """:
    #Given
    ...setup code...

    #When
    ...code that fetches/generates the HTML...

    #Then
    const tableEntrySelector = "table.table tr td a"
    check(html).toContainNthElements(tableEntrySelector, 1)
    check(html).select(tableEntrySelector).toHaveAttribute("href", "/potato/url")
```

At a glance, this could be integrated into HTest via the already existing `toHaveAttribute`.
Since templates can have default-arguments, you could just add a third parameter `value` with default value `""`.

Could look like this: `template toHaveAttribute*(hTest: HTest, attribute: string, value: string = "") =`.

**Comment by Yandall** [comment]
I just make the change for `toHaveAttribute` in the last update.
